rtl8188eu: Switch to `// fall through`
While compiling RTL8188EUS inline with Kernel, the following
warnings may occur:

  ../drivers/net/wireless/realtek/rtl8188eus/core/rtw_mlme_ext.c:1835:2:
  error: declaration does not declare anything
  [-Werror,-Wmissing-declarations]
          __attribute__ ((fallthrough));
          ^
    LD      drivers/misc/mediatek/built-in.o

  1 error generated.

and more.

Older GCC like 4.9 doesn't support this flag,
so switch to comment attribute for compatibility
flag.

Signed-off-by: Hendra Manudinata <hendra@manudinata.me>